#!/usr/bin/perl
# Reverse the encoding performed by the "encode" helper.
#
# This is not currently used by config-package-dev itself, but can by
# used by helper programs that want to determine what files are diverted
# by a package generated using this system.

use strict;
use warnings;
use Debian::Debhelper::config_package;

print decode($ARGV[0]);
